### PR TITLE
composer.json fixxed

### PR DESCRIPTION
**Pull request by Justman10000**
Came after the `composer install` command! That's how it works without any problems! Otherwise this error comes up:

grafik

### CODE REVIEW

**Comment by Tutorialwork** [comment]
Does this also solves the problem with Composer 2?

**Comment by Justman10000** [comment]
> Does this also solves the problem with Composer 2?

Well, it's weird that it works with my version of composer.json and not with the original one!

**Comment by Justman10000** [comment]
@Tutorialwork

**Comment by Justman10000** [comment]
@Tutorialwork

**Comment by Justman10000** [comment]
@Tutorialwork

**Pull request closed without merging**
